# Generated by Django 2.0.2 on 2018-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Собшение',
                'verbose_name_plural': 'Собшении',
            },
        ),
    ]
