# Generated by Django 2.0.2 on 2018-03-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_prosmotr'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dizlike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
